In [11]:
import pandas as pd 
import numpy as np 
import folium

ModuleNotFoundError: No module named 'folium'

In [10]:
h=pd.read_csv('data/homicide.csv')
h

,Country,Region,Subregion,Indicator,1990,1991,1992,1993,1994,1995,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Afghanistan,Asia,Southern Asia,Homicide Total Count,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1115.0,983.0,1231.0,1948.0,NaN,NaN,3367.0,2289.0,2515.0
1,Afghanistan,Asia,Southern Asia,Homicide Rate,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,3.4,4.1,6.3,NaN,NaN,10.0,6.6,7.1
2,Albania,Europe,Southern Europe,Homicide Total Count,NaN,NaN,130.0,191.0,112.0,259.0,...,93.0,85.0,127.0,142.0,157.0,124.0,117.0,82.0,99.0,68.0
3,Albania,Europe,Southern Europe,Homicide Rate,NaN,NaN,4.0,6.0,3.6,8.3,...,3.1,2.9,4.3,4.9,5.4,4.2,4.0,2.8,3.4,2.3
4,Algeria,Africa,Northern Africa,Homicide Total Count,NaN,NaN,NaN,NaN,NaN,NaN,...,328.0,277.0,254.0,280.0,523.0,480.0,577.0,542.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
475,Yemen,Asia,Western Asia,Homicide Rate,NaN,NaN,NaN,NaN,NaN,NaN,...,3.9,4.3,4.7,5.7,6.5,6.7,NaN,NaN,NaN,NaN
476,Zambia,Africa,Eastern Africa,Homicide Total Count,550.0,684.0,768.0,745.0,831.0,NaN,...,694.0,812.0,814.0,863.0,885.0,867.0,825.0,853.0,NaN,NaN
477,Zambia,Africa,Eastern Africa,Homicide Rate,6.9,8.3,9.1,8.6,9.3,NaN,...,5.3,6.0,5.9,6.0,6.0,5.7,5.3,5.3,NaN,NaN
478,Zimbabwe,Africa,Eastern Africa,Homicide Total Count,587.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,711.0,NaN,981.0,NaN,NaN,NaN,NaN,NaN
479,Zimbabwe,Africa,Eastern Africa,Homicide Rate,5.8,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,6.7,NaN,NaN,NaN,NaN,NaN